--Создаём директории
INSERT INTO DIRANDFILE(CREATED,PATH,DIRCNT,FILECNT,SUMMURYSIZE)
VALUES('2016-09-14 18:03:00','/opt/tomcat/temp',12,251,'128 MB');
INSERT INTO DIRANDFILE(CREATED,PATH,DIRCNT,FILECNT,SUMMURYSIZE)
VALUES('2016-09-14 10:27:00','/opt/tomcat/temp',12,51,'256 KB');

--Создаём файлы
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('<DIR>','innerTep',1);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('<DIR>','X-FILES',1);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('4,28Kb','f.txt',1);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('12,57Kb','F1.txt',1);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('1,52Mb','f4_99.JPG',1);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('901,48Kb','F4_00127.pdf',1);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
  VALUES('26,01Mb','f0008.doc',1);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('3,57Kb','function.cpp',1);

INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('<DIR>','innerTep',2);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('<DIR>','X-FILES',2);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('4,28Kb','f.txt',2);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('12,57Kb','F1.txt',2);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('1,52Mb','f4_99.JPG',2);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('901,48Kb','F4_00127.pdf',2);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
  VALUES('26,01Mb','f0008.doc',2);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('3,57Kb','function.cpp',2);