--Создаём директории
INSERT INTO DIRANDFILE(CREATED,PATH,DIRCNT,FILECNT,SUMMURYSIZE)
VALUES('2012-06-18 10:34:09','/home/',10,20,'12 MB');
INSERT INTO DIRANDFILE(CREATED,PATH,DIRCNT,FILECNT,SUMMURYSIZE)
VALUES('2012-06-11 10:34:09','/home123/',15,20,'6 KB');

--Создаём файлы
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('<DIR>','f1',1);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('<DIR>','f2',1);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('<DIR>','f1',2);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('<DIR>','f2',2);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('<DIR>','f3',2);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('3 KB','myFile',1);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('1 B','myFile2',1);
INSERT INTO HIERARHIFILES(SIZE,NAME,OWNERID)
VALUES('3 MB','myFile',2);

